spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: ${rds.driver}